docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - umask
    - ls -lR
    - umask 0022
    - umask
    - chmod -R og-w .
    - docker build -t jgoerzen/uucp .
    - docker tag jgoerzen/uucp jgoerzen/uucp:bullseye
    - docker push jgoerzen/uucp
    - docker push jgoerzen/uucp:bullseye
  only:
    - master

